# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestsDoublesSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestsDoublesSample
  def test_commons
    pod 'Quick'
    pod 'Nimble'
  end

  target 'TestsDoublesSampleHostedUnitTests' do
    inherit! :search_paths
    # Pods for testing
    test_commons
    pod 'Nimble-Snapshots'
  end

  target 'TestsDoublesSampleUnitTests' do
    inherit! :search_paths
    # Pods for testing
    test_commons
  end

end
